### ISSUE TITLE
Documentation of driver methods

### ISSUE THREAD

**Issue by guilinonline** [rlch/neogo#16]
只知道基本用法，不知道各方法的具体用法和作用，比如ReadSession用法，什么情况下用

**Comment by rlch** [comment]
You can find documentation here:

https://pkg.go.dev/github.com/rlch/neogo

Some APIs are more conducive to documentation through unit-tests than comments; see the example for `ReadSession` and other key-methods here:

https://pkg.go.dev/github.com/rlch/neogo#example-Driver-ReadSession
